<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>2a85ef84-6132-4a38-b015-494354518ec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='confirm-addresses']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;confirm-addresses&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>675071ee-1326-49f9-8960-49272bcc07c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f8bb5ce3-696a-4749-9208-6a2c67928767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>continue btn btn-primary float-xs-right</value>
      <webElementGuid>55eb6860-406d-4a00-8e2c-4c63028f0b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm-addresses</value>
      <webElementGuid>7455e9ce-26c3-49b9-87f3-caccf72ff463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ffccb186-9999-4abf-8daf-98e4fd880c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Continue
      </value>
      <webElementGuid>24fa0c0d-a986-4ee4-882d-bec27b47838c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery-address&quot;)/div[@class=&quot;js-address-form&quot;]/footer[@class=&quot;form-footer clearfix&quot;]/button[@class=&quot;continue btn btn-primary float-xs-right&quot;]</value>
      <webElementGuid>330b501f-cabb-41f9-9906-13f8d19979fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/spy/Page_PrestaShop Live Demo/iframe_Hide_framelive</value>
      <webElementGuid>1ecb05b4-efc8-4c2f-be75-0870928fa160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='confirm-addresses']</value>
      <webElementGuid>54c4ea51-fde6-4309-9c2b-13e6eeaa1793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delivery-address']/div/footer/button</value>
      <webElementGuid>db697778-28b5-4fb6-9484-ae890f7d4eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use this address for invoice too'])[1]/following::button[1]</value>
      <webElementGuid>47ba411b-9ee0-495a-bdc9-19a7008a5d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional'])[4]/following::button[1]</value>
      <webElementGuid>ca580086-329b-43c9-9168-cd79a63a7ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>63fa3798-cc9f-40f4-8a6a-6bc62571cd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'confirm-addresses' and (text() = '
          Continue
      ' or . = '
          Continue
      ')]</value>
      <webElementGuid>33300735-0947-4702-805f-3be6c2f1d73e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
