<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Hide_framelive</name>
   <tag></tag>
   <elementGuidId>3e7a121f-d1cd-49c3-bf10-2031488e7559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='framelive']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#framelive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;framelive&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e73520d9-9447-4f06-974c-8c72b1d25b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Frame of demo shop</value>
      <webElementGuid>46ce0254-c91d-4598-a825-139095823072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>framelive</value>
      <webElementGuid>b1eef655-672b-45f9-809c-2db2621be138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>framelive</value>
      <webElementGuid>40019749-b4b0-40e8-8cf7-b815b16faf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0a1a8f09-9ad7-4290-8a57-b146af045ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://spotty-scarecrow.demo.prestashop.com/en/?id_module_showcased=undefined</value>
      <webElementGuid>97e8daca-7366-4b5b-ae1e-10b3a13a5a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;framelive&quot;)</value>
      <webElementGuid>503f0206-3ffa-4fd5-8b7a-ef04c3d91e56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='framelive']</value>
      <webElementGuid>83283fa0-76de-448e-a6e3-d0d694d80b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframe-wrapper']/iframe</value>
      <webElementGuid>f3ec8a5e-6bb5-404b-9bc3-25b674047450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2fac697c-d5cd-4d73-814d-d3af32b4e714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Frame of demo shop' and @id = 'framelive' and @name = 'framelive' and @src = 'https://spotty-scarecrow.demo.prestashop.com/en/?id_module_showcased=undefined']</value>
      <webElementGuid>65dd28b4-760a-4dc9-ac39-e5851dfee8fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
